### ISSUE TITLE
Issue when unpack .FXB 

### ISSUE THREAD

**Issue by minhmc2007** [Sor3nt/manhunt-toolkit#44]
![Screenshot_20241208_091504_Termux.jpg](https://github.com/user-attachments/assets/7b19fdb0-d980-4ca7-af4d-2bcc230ecea1)

**Comment by minhmc2007** [comment]
If possible can you unpack this file(https://drive.google.com/file/d/1YEfUFAiS68je7iOymtgBd59OG4a1jdQn/view?usp=drivesdk) github mobile not allow me to send this file.

**Comment by minhmc2007** [comment]
Idk why but after reinstall my linux system the problem fixed but why this tool is not supported pack .FXB ?

**Comment by Sor3nt** [comment]
^^. FXB is still in progress, many fields are unknown so a packing process make no sense yet

**Comment by minhmc2007** [comment]
Bro I believe the .FXB file is related to the blood effects during executions. Here's what I tried:
1. The file is in the sfx folder, which I think handles special effects.
2. I replaced it with the beta PSP .FXB, but that broke all blood effects—now they're completely gone.
3. Then I tried merging it with the PS2 beta .FXB. It worked perfectly, but the blood on the camera still wasn't gorier like in the beta.
Do you know why this happens? Are .FXB files platform-specific or restricted? (my goal is to make manhunt 2 psp game more bloody) 
You this is my mod(still underdevelopment):https://minhmc2007.github.io/The-project-gore-manhunt-2-psp-website/

**Comment by Sor3nt** [comment]
they are differents. some platform use plain text FXB which is not compatible with mh2 pc, some use a older version on FXB compared to MH2, merging them is not easy without to know all required fields.

also the camera blood is part of the animation, each execution animation has a effect block for the camera blood effects. also here. its not supported yet (correction, it is supported but not decoded)

**Comment by minhmc2007** [comment]
https://github.com/user-attachments/assets/7bfb9e1c-f3e0-451e-926a-ccb36bdad321

**Comment by Sor3nt** [comment]
this is the animation blood effect. not FXB

unpack the wanted execution, open the JSON and scroll to the bottom, the effect section is there

**Comment by minhmc2007** [comment]
What is execution file ? Animation but which file maybe ALLANIMS.IFP ?

**Comment by Sor3nt** [comment]
strmanim_pc.bin

**Comment by minhmc2007** [comment]
Psp bro

**Comment by Sor3nt** [comment]
STRMANIM.BIN

**Comment by minhmc2007** [comment]
u0_a322@localhost ~/s/d/A/M/P/U/L/A01_ES> mht unpack STRMANIM mh2 psp

███╗   ███╗██╗  ██╗████████╗    ██╗   ██╗   ██████╗    █████╗
████╗ ████║██║  ██║╚══██╔══╝    ██║   ██║  ██╔═████╗  ██╔══██╗
██╔████╔██║███████║   ██║       ██║   ██║  ██║██╔██║  ╚██████║
██║╚██╔╝██║██╔══██║   ██║       ╚██╗ ██╔╝  ████╔╝██║   ╚═══██║
██║ ╚═╝ ██║██║  ██║   ██║        ╚████╔╝██╗╚██████╔╝██╗█████╔╝
╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝         ╚═══╝ ╚═╝ ╚═════╝ ╚═╝╚════╝ 2024-09
                        Coded by Sor3nt | dixmor-hospital.com
A free and open source toolkit to quickly modify Rockstar`s game Manhunt.


Fatal error: Uncaught ErrorException: Undefined array key "dirname" in phar:///data/data/com.termux/files/home/manhunt-toolkit/mht.phar/App/Service/MyFinder.php:16
Stack trace:
#0 phar:///data/data/com.termux/files/home/manhunt-toolkit/mht.phar/App/Service/MyFinder.php(16): exception_error_handler(2, 'Undefined array...', 'phar:///data/da...', 16)
#1 phar:///data/data/com.termux/files/home/manhunt-toolkit/mht.phar/App/Commands/unpack.php(48): App\Service\MyFinder->__construct('')
#2 phar:///data/data/com.termux/files/home/manhunt-toolkit/mht.phar/mht.php(122): include('phar:///data/da...')
#3 /data/data/com.termux/files/home/manhunt-toolkit/mht.phar(10): include('phar:///data/da...')
#4 {main}
  thrown in phar:///data/data/com.termux/files/home/manhunt-toolkit/mht.phar/App/Service/MyFinder.php on line 16

**Comment by Sor3nt** [comment]
<img width="1568" alt="Bildschirmfoto 2025-01-10 um 12 16 39" src="https://github.com/user-attachments/assets/d7d5b7c5-11d5-4481-8dea-1b0ee113ac29" />

**Comment by Sor3nt** [comment]
your file is wrong, missed .BIN ?!

**Comment by minhmc2007** [comment]
damn, sorry bro

**Comment by minhmc2007** [comment]
This ?
![Screenshot_20250110_183252_ZArchiver](https://github.com/user-attachments/assets/21ab7bf8-c800-4e3d-b34b-87e9a7f3e6b5)

**Comment by Sor3nt** [comment]
yep

**Comment by minhmc2007** [comment]
lbloodf? Location? how bro? Help me. 😔 bro it's beyond my understanding

**Comment by Sor3nt** [comment]
like i said, this section was not decoded yet, i can not help ya, u need to play around

**Comment by minhmc2007** [comment]
Or just remove the alpha channel in the TXD files? it will make the blood no longer have transparency.

**Comment by minhmc2007** [comment]
Sor3nt do you know how to compile manhunt 2 psp debug menu, do i need to install pspsdk?

**Comment by minhmc2007** [comment]
![Screenshot_20250111_114318_PPSSPP Gold](https://github.com/user-attachments/assets/cb4e63fc-a0cc-434f-b17b-74434e5f9e7d)
Still dont know how to bring that blood to the manhunt 2 offical version

**Comment by minhmc2007** [comment]
Hi Sor3nt, long time no see. Can i ask you a question. Which files contain execution sound Mh2?

**Comment by Hellwire** [comment]
Executions.fsb use the 0.9.5 release for that

**Comment by minhmc2007** [comment]
> Executions.fsb use the 0.9.5 release for that

Psp version?

**Comment by Hellwire** [comment]
The psp store the execution audio in the level folder. AUD_PSP.AFS -> execute

**Comment by minhmc2007** [comment]
> The psp store the execution audio in the level folder. AUD_PSP.AFS -> execute

Thx but i cant pack it ![Screenshot_20250309_171401_NetHunter Terminal.jpg](https://github.com/user-attachments/assets/13d3f0d4-1c3c-414d-877f-8bdac295a0d8)

**Comment by Hellwire** [comment]
For afs paking you need to use afspacker
